# Created by trellis-cli v0.6.0
# Documentation: https://roots.io/trellis/docs/wordpress-sites/

wordpress_sites:
  waterfairi.es:
    site_hosts:
    - canonical: waterfairi.es
    local_path: ../site
    branch: master
    repo: git@github.com:neilgilmour/waterfairi.es.git
    repo_subtree_path: site
    multisite:
      enabled: false
    ssl:
      enabled: true
      provider: letsencrypt
    cache:
      enabled: false
